# Generated by Django 4.2.2 on 2024-03-07 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.TextField()),
                ('name', models.CharField(max_length=100)),
                ('sku', models.IntegerField()),
                ('Quantity', models.IntegerField()),
            ],
        ),
    ]
